site_name: Trilha Dev
site_url: https://trilhadev.planejamento.mg.gov.br/

# Repository
repo_name: splor-mg/trilha-dev
repo_url: https://github.com/splor-mg/trilha-dev
edit_uri: edit/main/docs/

nav:
  - Início: 
    - index.md
    - Início da Jornada: 
      - inicio_da_jornada/index.md
      - Aulas: 
        - Dia 01: inicio_da_jornada/aulas/dia_01/dia_01.md
        - Dia 02: inicio_da_jornada/aulas/dia_02/dia_02.md
        - Dia 03: inicio_da_jornada/aulas/dia_03/dia_03.md
        - Dia 04: inicio_da_jornada/aulas/dia_04/dia_04.md
        - Dia 05: inicio_da_jornada/aulas/dia_05/dia_05.md
        - Dia 06: inicio_da_jornada/aulas/dia_06/dia_06.md
      - Desafio Final: inicio_da_jornada/desafio_final.md
      - Registos da 1ª Turma: inicio_da_jornada/turma_01/registros_encontros.md
      - Certificação: inicio_da_jornada/certificacao.md
    - Python:
      - python/index.md
      - Aulas:
        - Aula 001: python/aulas/001_primeiro_programa_py.md
        - Aula 002: python/aulas/002_como_py_executado.md
        - Aula 003: python/aulas/003_variaveis.md

# Configuration
theme:
  name: material
  language: pt
  logo: assets/logo.png
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.expand
  palette:
    - scheme: slate
      primary: lime #cbdc39
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo claro
    - scheme: defaut
      primary: lime #cbdc39
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Modo Escuro
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: pt
  - social
  - mkdocs_quiz:
  - charts

# Custom CSS
extra_css:
  - assets/style.css

extra:
  version:
    provider: mike

extra:
  include_cname: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
